# Generated by Django 4.2.1 on 2023-05-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('supplier', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('recipient', models.CharField(max_length=250)),
                ('employee_id', models.IntegerField()),
                ('date_of_payment', models.CharField(max_length=250)),
            ],
        ),
    ]
